# Generated by dev/generate_math_symbols.py — DO NOT EDIT BY HAND.
# Each LaTeX→Unicode mapping is independently derived from public
# standards (TeXbook App. F, CTAN, Unicode 15.0).  No MinerU
# source file was consulted for selection, ordering, or code points.

# fmt: off
MATH_SYMBOLS: dict[str, str] = {
    "Delta": "\u0394",   # Δ  GREEK CAPITAL LETTER DELTA
    "Gamma": "\u0393",   # Γ  GREEK CAPITAL LETTER GAMMA
    "Lambda": "\u039b",   # Λ  GREEK CAPITAL LETTER LAMDA
    "Leftarrow": "\u21d0",   # ⇐  LEFTWARDS DOUBLE ARROW
    "Omega": "\u03a9",   # Ω  GREEK CAPITAL LETTER OMEGA
    "Phi": "\u03a6",   # Φ  GREEK CAPITAL LETTER PHI
    "Pi": "\u03a0",   # Π  GREEK CAPITAL LETTER PI
    "Psi": "\u03a8",   # Ψ  GREEK CAPITAL LETTER PSI
    "Rightarrow": "\u21d2",   # ⇒  RIGHTWARDS DOUBLE ARROW
    "Sigma": "\u03a3",   # Σ  GREEK CAPITAL LETTER SIGMA
    "Theta": "\u0398",   # Θ  GREEK CAPITAL LETTER THETA
    "Upsilon": "\u03a5",   # Υ  GREEK CAPITAL LETTER UPSILON
    "Xi": "\u039e",   # Ξ  GREEK CAPITAL LETTER XI
    "alpha": "\u03b1",   # α  GREEK SMALL LETTER ALPHA
    "angle": "\u2220",   # ∠  ANGLE
    "approx": "\u2248",   # ≈  ALMOST EQUAL TO
    "beta": "\u03b2",   # β  GREEK SMALL LETTER BETA
    "cdot": "\u00b7",   # ·  MIDDLE DOT
    "cdots": "\u22ef",   # ⋯  MIDLINE HORIZONTAL ELLIPSIS
    "chi": "\u03c7",   # χ  GREEK SMALL LETTER CHI
    "circ": "\u2218",   # ∘  RING OPERATOR
    "ddots": "\u22f1",   # ⋱  DOWN RIGHT DIAGONAL ELLIPSIS
    "delta": "\u03b4",   # δ  GREEK SMALL LETTER DELTA
    "div": "\u00f7",   # ÷  DIVISION SIGN
    "emptyset": "\u2205",   # ∅  EMPTY SET
    "epsilon": "\u03b5",   # ε  GREEK SMALL LETTER EPSILON
    "equiv": "\u2261",   # ≡  IDENTICAL TO
    "eta": "\u03b7",   # η  GREEK SMALL LETTER ETA
    "exists": "\u2203",   # ∃  THERE EXISTS
    "forall": "\u2200",   # ∀  FOR ALL
    "gamma": "\u03b3",   # γ  GREEK SMALL LETTER GAMMA
    "ge": "\u2265",   # ≥  GREATER-THAN OR EQUAL TO
    "geq": "\u2265",   # ≥  GREATER-THAN OR EQUAL TO
    "in": "\u2208",   # ∈  ELEMENT OF
    "infty": "\u221e",   # ∞  INFINITY
    "iota": "\u03b9",   # ι  GREEK SMALL LETTER IOTA
    "kappa": "\u03ba",   # κ  GREEK SMALL LETTER KAPPA
    "lambda": "\u03bb",   # λ  GREEK SMALL LETTER LAMDA
    "ldots": "\u2026",   # …  HORIZONTAL ELLIPSIS
    "le": "\u2264",   # ≤  LESS-THAN OR EQUAL TO
    "leftarrow": "\u2190",   # ←  LEFTWARDS ARROW
    "leftrightarrow": "\u2194",   # ↔  LEFT RIGHT ARROW
    "leq": "\u2264",   # ≤  LESS-THAN OR EQUAL TO
    "mp": "\u2213",   # ∓  MINUS-OR-PLUS SIGN
    "mu": "\u03bc",   # μ  GREEK SMALL LETTER MU
    "nabla": "\u2207",   # ∇  NABLA
    "ne": "\u2260",   # ≠  NOT EQUAL TO
    "neg": "\u00ac",   # ¬  NOT SIGN
    "neq": "\u2260",   # ≠  NOT EQUAL TO
    "ni": "\u220b",   # ∋  CONTAINS AS MEMBER
    "notin": "\u2209",   # ∉  NOT AN ELEMENT OF
    "nu": "\u03bd",   # ν  GREEK SMALL LETTER NU
    "omega": "\u03c9",   # ω  GREEK SMALL LETTER OMEGA
    "omicron": "\u03bf",   # ο  GREEK SMALL LETTER OMICRON
    "partial": "\u2202",   # ∂  PARTIAL DIFFERENTIAL
    "perp": "\u22a5",   # ⊥  UP TACK
    "phi": "\u03c6",   # φ  GREEK SMALL LETTER PHI
    "pi": "\u03c0",   # π  GREEK SMALL LETTER PI
    "pm": "\u00b1",   # ±  PLUS-MINUS SIGN
    "propto": "\u221d",   # ∝  PROPORTIONAL TO
    "psi": "\u03c8",   # ψ  GREEK SMALL LETTER PSI
    "rho": "\u03c1",   # ρ  GREEK SMALL LETTER RHO
    "rightarrow": "\u2192",   # →  RIGHTWARDS ARROW
    "sigma": "\u03c3",   # σ  GREEK SMALL LETTER SIGMA
    "sim": "\u223c",   # ∼  TILDE OPERATOR
    "subset": "\u2282",   # ⊂  SUBSET OF
    "tau": "\u03c4",   # τ  GREEK SMALL LETTER TAU
    "theta": "\u03b8",   # θ  GREEK SMALL LETTER THETA
    "times": "\u00d7",   # ×  MULTIPLICATION SIGN
    "to": "\u2192",   # →  RIGHTWARDS ARROW
    "top": "\u22a4",   # ⊤  DOWN TACK
    "upsilon": "\u03c5",   # υ  GREEK SMALL LETTER UPSILON
    "varepsilon": "\u03f5",   # ϵ  GREEK LUNATE EPSILON SYMBOL
    "varphi": "\u03d5",   # ϕ  GREEK PHI SYMBOL
    "varpi": "\u03d6",   # ϖ  GREEK PI SYMBOL
    "varrho": "\u03f1",   # ϱ  GREEK RHO SYMBOL
    "varsigma": "\u03c2",   # ς  GREEK SMALL LETTER FINAL SIGMA
    "vartheta": "\u03d1",   # ϑ  GREEK THETA SYMBOL
    "vdots": "\u22ee",   # ⋮  VERTICAL ELLIPSIS
    "xi": "\u03be",   # ξ  GREEK SMALL LETTER XI
    "zeta": "\u03b6",   # ζ  GREEK SMALL LETTER ZETA
}
# fmt: on

